#!/bin/sh

PATH=/var/qmail/bin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin
export PATH

QMAILDUID=`id -u qmaild`
NOFILESGID=`id -g qmaild`

case "$1" in
  start)
    echo "Starting qmail"
    for service in /service/qmail-*; do 
      servicename=`basename $service`
      if svok $service ; then
        svc -u $service $service/log
	echo "  $servicename"
      else
        echo " $servicename supervise not running"
      fi
    done
    if [ -d /var/lock/subsys ]; then
      touch /var/lock/subsys/qmail
    fi
    ;;
  stop)
    echo "Stopping qmail..."
    for service in /service/qmail-*; do
      servicename=`basename $service`
      echo "  $servicename"
      svc -d $service $service/log
    done
    if [ -f /var/lock/subsys/qmail ]; then
      rm /var/lock/subsys/qmail
    fi
    ;;
  stat)
    for service in /service/qmail-*; do
      svstat $service
      svstat $service/log
    done
    qmail-qstat
    ;;
  doqueue|alrm|flush)
    echo "Flushing timeout table and sending ALRM signal to qmail-send."
    /var/qmail/bin/qmail-tcpok
    svc -a /service/qmail-send
    ;;
  queue)
    qmail-qstat
    qmail-qread
    ;;
  reload|hup)
    echo "Sending HUP signal to qmail-send."
    svc -h /service/qmail-send
    ;;
  pause)
    for service in /service/qmail-*; do
      servicename=`basename $service`
      echo "Pausing $servicename"
      svc -p $service
    done
    ;;
  cont)
    for service in /service/qmail-*; do
      servicename=`basename $service`
      echo "Continuing $servicename"
      svc -c $service
    done
    ;;
  restart)
    echo "Restarting qmail:"
    $0 stop
    $0 start
    ;;
  cdb)
    for cdb in /var/qmail/etc/tcp.*.cdb; do
      tcprules $cdb ${cdb}.tmp < ${cdb%.cdb}
      chmod 644 $cdb
      echo "Reloaded $cdb"
    done
    ;;
  rotate)
    for service in /service/qmail-*/log; do
      echo "Rotating $service"
      svc -a $service
    done
    ;;
  help)
    cat <<HELP
   stop -- stops mail service (smtp connections refused, nothing goes out)
  start -- starts mail service (smtp connection accepted, mail can go out)
  pause -- temporarily stops mail service (connections accepted, nothing leaves)
 rotate -- rotate all logfiles (sending ALRM to multilog)
   cont -- continues paused mail service
   stat -- displays status of mail service
    cdb -- rebuild the tcpserver cdb file for smtp
restart -- stops and restarts smtp, sends qmail-send a TERM & restarts it
doqueue -- schedules queued messages for immediate delivery
 reload -- sends qmail-send HUP, rereading locals and virtualdomains
  queue -- shows status of queue
   alrm -- same as doqueue
  flush -- same as doqueue
    hup -- same as reload
HELP
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|doqueue|flush|reload|stat|pause|cont|cdb|queue|help}"
    exit 1
    ;;
esac

exit 0

